// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/helloworlde.proto

package helloworlde

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v3/api"
	client "github.com/micro/go-micro/v3/client"
	server "github.com/micro/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Helloworlde service

func NewHelloworldeEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Helloworlde service

type HelloworldeService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Helloworlde_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Helloworlde_PingPongService, error)
}

type helloworldeService struct {
	c    client.Client
	name string
}

func NewHelloworldeService(name string, c client.Client) HelloworldeService {
	return &helloworldeService{
		c:    c,
		name: name,
	}
}

func (c *helloworldeService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Helloworlde.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloworldeService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Helloworlde_StreamService, error) {
	req := c.c.NewRequest(c.name, "Helloworlde.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &helloworldeServiceStream{stream}, nil
}

type Helloworlde_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type helloworldeServiceStream struct {
	stream client.Stream
}

func (x *helloworldeServiceStream) Close() error {
	return x.stream.Close()
}

func (x *helloworldeServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *helloworldeServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloworldeServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloworldeServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloworldeService) PingPong(ctx context.Context, opts ...client.CallOption) (Helloworlde_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Helloworlde.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &helloworldeServicePingPong{stream}, nil
}

type Helloworlde_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type helloworldeServicePingPong struct {
	stream client.Stream
}

func (x *helloworldeServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *helloworldeServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *helloworldeServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloworldeServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloworldeServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *helloworldeServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Helloworlde service

type HelloworldeHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Helloworlde_StreamStream) error
	PingPong(context.Context, Helloworlde_PingPongStream) error
}

func RegisterHelloworldeHandler(s server.Server, hdlr HelloworldeHandler, opts ...server.HandlerOption) error {
	type helloworlde interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Helloworlde struct {
		helloworlde
	}
	h := &helloworldeHandler{hdlr}
	return s.Handle(s.NewHandler(&Helloworlde{h}, opts...))
}

type helloworldeHandler struct {
	HelloworldeHandler
}

func (h *helloworldeHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.HelloworldeHandler.Call(ctx, in, out)
}

func (h *helloworldeHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.HelloworldeHandler.Stream(ctx, m, &helloworldeStreamStream{stream})
}

type Helloworlde_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type helloworldeStreamStream struct {
	stream server.Stream
}

func (x *helloworldeStreamStream) Close() error {
	return x.stream.Close()
}

func (x *helloworldeStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *helloworldeStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloworldeStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloworldeStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *helloworldeHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.HelloworldeHandler.PingPong(ctx, &helloworldePingPongStream{stream})
}

type Helloworlde_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type helloworldePingPongStream struct {
	stream server.Stream
}

func (x *helloworldePingPongStream) Close() error {
	return x.stream.Close()
}

func (x *helloworldePingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *helloworldePingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloworldePingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloworldePingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *helloworldePingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
